Тест
YuliyaStasyeva/Apinist pull request #4
Opened 2019-01-08 14:39 UTC by YuliyaStasyeva

2019-01-08 15:05 UTC, Per4uk93-zz requested changes

2019-01-08 15:05 UTC, Per4uk93 commented on po_main.js
> +          var EC=protractor.ExpectedConditions;
var?

2019-01-09 09:08 UTC, YuliyaStasyeva reviewed
FIX

2019-01-09 09:08 UTC, YuliyaStasyeva commented on po_main.js
> +          await browser.wait(EC.presenceOf(elseLink), 10000);
Исправлено

2019-01-09 09:08 UTC, YuliyaStasyeva commented on po_location.js
> +          await browser.wait(EC.visibilityOf(selectInput, 10000));
Исправлено

2019-01-09 09:09 UTC, YuliyaStasyeva commented on po_main.js
> +          var parisList=await getCityArray.getText();
let

2019-01-09 10:48 UTC, YuliyaStasyeva commented
[README.txt](https://github.com/YuliyaStasyeva/Apinist/files/2740520/README.txt)

2019-01-21 15:09 UTC, closed without merging